# .woodpecker.yml
pipeline:
  check-versions:
    image: ubuntu:22.04
    commands:
      - export URL=`curl -H "user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36" https://www.minecraft.net/en-us/download/server/bedrock|grep -o "https://minecraft.azureedge.net/bin-linux/bedrock-server-.*.zip"`
      - export VERSION=`echo $URL|grep -o "[0-9.]*[0-9]"`
      - export MATCHING=`curl https://nexusdocker.local/v2/acbgbca/minecraft-bedrock-docker/tags/list|grep "$VERSION"`
      - export CREATE=${MATCHING:true};
  builder:
    image: plugins/docker
    when:
      matrix:
        CREATE: true
    settings:
      username: $DOCKER_USERNAME
      password: $DOCKER_PASSWORD
      repo: nexusdocker.local/acbgbca/minecraft-bedrock-docker
      tags:
        - latest
        - $VERSION
    secrets: [docker_username, docker_password]
