pool:
  name: SelfHosted

trigger:
- master

resources:
- repo: self

stages:
- stage: Build
  displayName: Check versions
  jobs:
  - job: check
    displayName: Check
    steps:
    - bash: |
         URL=`curl -H "user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36" https://www.minecraft.net/en-us/download/server/bedrock|grep -o "https://minecraft.azureedge.net/bin-linux/bedrock-server-.*.zip"`
         VERSION=`echo $URL|grep -o "[0-9.]*[0-9]"`
         MATCHING=`curl http://dockerregistry:5000/v2/acbgbca/minecraft-bedrock-docker/tags/list|grep "$VERSION"`
         CREATE=${MATCHING:-true}
         # Store values for use in later stages
         echo "##vso[task.setvariable variable=URL;isOutput=true]$URL"
         echo "##vso[task.setvariable variable=VERSION;isOutput=true]$VERSION"
         echo "##vso[task.setvariable variable=CREATE;isOutput=true]$CREATE"
         echo "URL: $URL"
         echo "VERSION: $VERSION"
         echo "MATCHING: $MATCHING"
         echo "CREATE: $CREATE"
      name: check
  - job: debug
    dependsOn: check
    variables:
      URL: $[ dependencies.check.outputs['check.URL'] ]
      VERSION: $[ dependencies.check.outputs['check.VERSION'] ]
    steps:
    - bash: |
        echo "URL: $(URL)"
        echo "VERSION: $(VERSION)"
  - job: Build
    dependsOn: check
    variables:
      URL: $[ dependencies.check.outputs['check.URL'] ]
      VERSION: $[ dependencies.check.outputs['check.VERSION'] ]
    condition: eq(dependencies.check.outputs['check.CREATE'], 'true')
    displayName: Build
    steps:
    - bash: |
        curl $(URL) --output bedrock-server-$(VERSION).zip
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHub'
        command: 'login'
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: buildAndPush
        dockerfile: '$(Build.SourcesDirectory)/dockerfile'
        tags: |
          latest
          $(VERSION)
