name: Minecraft Bedrock Docker

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - 'main'
      - 'master'

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - id: version
        run: |
          # Make sure we have the latest version
          docker pull acbca/minecraft-bedrock
          URL=`curl -H "user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36" https://www.minecraft.net/en-us/download/server/bedrock|grep -o "https://minecraft.azureedge.net/bin-linux/bedrock-server-.*.zip"`
          VERSION=`echo $URL|grep -o "[0-9.]*[0-9]"`
          VERSION_MAJOR=`echo $VERSION|grep -o "[0-9]*\.[0-9]*"|head -1`
          MATCHING=`docker image ls acbca/minecraft-bedrock:*|grep "$VERSION"`
          CREATE=${MATCHING:-true}
          # Store values for use in later stages
          echo "::set-output name=url::$URL"
          echo "::set-output name=version::$VERSION"
          echo "::set-output name=version_major::$VERSION_MAJOR"
          echo "::set-output name=create::$CREATE"
          echo "URL: $URL"
          echo "VERSION: $VERSION"
          echo "MAJOR VERSION: $VERSION_MAJOR"
          echo "MATCHING: $MATCHING"
          echo "CREATE: $CREATE"
    outputs: 
      url: ${{steps.version.outputs.url}}
      version: ${{steps.version.outputs.version}}
      version_major: ${{steps.version.outputs.version_major}}
      create: ${{steps.version.outputs.create}}
  build-main:
    needs: check-version
    if: env.create == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            acbca/minecraft-bedrock:latest
            acbca/minecraft-bedrock:${{needs.version.outputs.version}}
            acbca/minecraft-bedrock:${{needs.version.outputs.major_version}}
          build-args: |
            URL=${{needs.version.outputs.url}}
            VERSION=${{needs.version.outputs.version}}