name: Minecraft Bedrock Docker

on:
  schedule:
    - cron: "0 0 * * *"
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
      - '.github/renovate.json'
      - '.github/workflows/renovate.yaml'
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
      - '.github/renovate.json'
      - '.github/workflows/renovate.yaml'

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - id: version
        shell: bash
        run: |
          # echo on for debugging
          set -x
          # Don't die on error (docker pull returns an error if the version doesn't exist)
          set +e
          URL=`curl -H "user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36" https://www.minecraft.net/en-us/download/server/bedrock|grep -o "https://minecraft.azureedge.net/bin-linux/bedrock-server-.*.zip"`
          VERSION=`echo $URL|grep -o "[0-9.]*[0-9]"`
          VERSION_MAJOR=`echo $VERSION|grep -o "[0-9]*\.[0-9]*"|head -1`
          # Check for version
          MATCHING=$(docker pull acbca/minecraft-bedrock:$VERSION)
          if [ -z "$MATCHING" ]; then
            CREATE="true"
          else
            CREATE="false"
          fi
          # Store values for use in later stages
          echo "url=$URL" >> $GITHUB_ENV 
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "version_major=$VERSION_MAJOR" >> $GITHUB_ENV
          echo "create=$CREATE" >> $GITHUB_ENV
          echo "URL: $URL"
          echo "VERSION: $VERSION"
          echo "MAJOR VERSION: $VERSION_MAJOR"
          echo "CREATE: $CREATE"
    outputs: 
      url: ${{env.url}}
      version: ${{env.version}}
      version_major: ${{env.version_major}}
      create: ${{env.create}}
  debug:
    needs: check-version
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Create: ${{needs.check-version.outputs.create}}"
          echo "URL: ${{needs.check-version.outputs.url}}"
          echo "Version: ${{needs.check-version.outputs.version}}"
          echo "Major Version: ${{needs.check-version.outputs.version_major}}"
          echo "github.ref: ${{github.ref}}"
          echo "github.event: ${{github.event}}"
          echo "github.event.pull_request.merged: ${{github.event.pull_request.merged}}"
          echo "github.event_name: ${{github.event_name}}"
  build-main:
    needs: check-version
    if: ${{ needs.check-version.outputs.create == 'true' || ( github.ref == 'refs/heads/main' && github.event_name == 'push' ) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
        # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: |
            acbgbca/minecraft-bedrock-docker
            ghcr.io/acbgbca/minecraft-bedrock-docker
          labels: |
            org.opencontainers.image.title=Minecraft Bedrock Server - Docker
            org.opencontainers.image.version=${{needs.check-version.outputs.version}}
          annotations: |
            org.opencontainers.image.title=Minecraft Bedrock Server - Docker
            org.opencontainers.image.version=${{needs.check-version.outputs.version}}
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3.6.1
      - name: Login to DockerHub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Log in to the Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v6.7.0
        with:
          context: .
          load: true
          tags: |
            acbgbca/minecraft-bedrock:test
          build-args: |
            URL=${{needs.check-version.outputs.url}}
            VERSION=${{needs.check-version.outputs.version}}
      - name: Verify image
        run: |
          docker run --rm -e EULA=TRUE acbgbca/minecraft-bedrock:test ./verify.sh
      - name: Push
        uses: docker/build-push-action@v6.7.0
        with:
          context: .
          push: true
          tags: |
            acbca/minecraft-bedrock:latest
            acbca/minecraft-bedrock:${{needs.check-version.outputs.version}}
            acbca/minecraft-bedrock:${{needs.check-version.outputs.version_major}}
            ghcr.io/acbgbca/minecraft-bedrock:latest
            ghcr.io/acbgbca/minecraft-bedrock:${{needs.check-version.outputs.version}}
            ghcr.io/acbgbca/minecraft-bedrock:${{needs.check-version.outputs.version_major}}
          annotations: ${{ steps.meta.outputs.annotations }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            URL=${{needs.check-version.outputs.url}}
            VERSION=${{needs.check-version.outputs.version}}
  build-alpha:
    needs: check-version
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
        # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: |
            acbgbca/minecraft-bedrock-docker
            ghcr.io/acbgbca/minecraft-bedrock-docker
          labels: |
            org.opencontainers.image.title=Minecraft Bedrock Server - Docker
            org.opencontainers.image.version=${{needs.check-version.outputs.version}}
          annotations: |
            org.opencontainers.image.title=Minecraft Bedrock Server - Docker
            org.opencontainers.image.version=${{needs.check-version.outputs.version}}
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3.6.1
      - name: Login to DockerHub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Log in to the Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v6.7.0
        with:
          context: .
          load: true
          tags: |
            acbgbca/minecraft-bedrock:test
          build-args: |
            URL=${{needs.check-version.outputs.url}}
            VERSION=${{needs.check-version.outputs.version}}
      - name: Verify image
        run: |
          docker run --rm -e EULA=TRUE acbgbca/minecraft-bedrock:test ./verify.sh
      - name: Push
        uses: docker/build-push-action@v6.7.0
        with:
          context: .
          push: true
          tags: |
            acbca/minecraft-bedrock:alpha
            acbca/minecraft-bedrock:alpha-${{needs.check-version.outputs.version}}
            acbca/minecraft-bedrock:alpha-${{needs.check-version.outputs.version_major}}
            ghcr.io/acbgbca/minecraft-bedrock:alpha
            ghcr.io/acbgbca/minecraft-bedrock:alpha-${{needs.check-version.outputs.version}}
            ghcr.io/acbgbca/minecraft-bedrock:alpha-${{needs.check-version.outputs.version_major}}
          annotations: ${{ steps.meta.outputs.annotations }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            URL=${{needs.check-version.outputs.url}}
            VERSION=${{needs.check-version.outputs.version}}